<a href="https://colab.research.google.com/github/purple0607/Linear-Algebra_2nd-Sem/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 2 : Matrices


In the previous laboratory activity, the students have learned and applied the basic concepts, principles, and techniques of Python fundamentals. However, this laboratory activity focuses on the application of matrices in Python in relation to the linear system of equations. Through this activity, the students will be able to learn the application of matrices in programming together with its basic operations and techniques. Upon learning its applications, the students will be able to apply their knowledge in translating matrix equations and operations using Python.

# Discussion

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

- Numerical Python or "numpy" in short, supports a broad range of mathematical operations on arrays. It extends Python with sophisticated data formats that ensure fast array and matrix computations, as well as a vast library of elevated numerical methods that work on these matrices and arrays [1].
- Matplotlib.pyplot is a set of algorithms that enable matplotlib to operate similarly to MATLAB. Each pyplot function modifies a figure in a certain way [2]
- Scipy.linalg contains a variety of tools for solving linear algebra applications, such as functions for conducting matrix operations [3].


### Matrices




A matrix is a two-dimensional rectangle array that holds data in rows and columns. The matrix may hold any form of data, including numbers, strings, equations, and so on. The data is organized horizontally as rows and vertically as columns. Matrix data structures, on the other hand, are vital for various mathematical and scientific operations [4].

Matrix notation and utilization is likely one of the three cornerstones of modern calculations. Matrices are also useful for representing complicated equations or several interconnected equations, ranging from two-dimensional equations to the desired number of equations [2].




For instance, let $F$, $G$, and $H$ as a system of equations.


$$
F = \left\{
    \begin{array}\
        l + 2m \\
        7m - 11l
    \end{array}
\right. \\
G = \left\{
    \begin{array}\
        13l + m- 7n \\
        -8l + 21m -n \\
        17l -6m +1n
    \end{array}\
\right. \\
H = \left\{
    \begin{array}\
        9k +40l +m +3n \\
        3k+ l +4m -81n \\
        -6k -5l + 41m -11n \\
        51k +l -3m +n
    \end{array}
\right. $$

In this representation, we could observe that $F$ is a system of 2 equations with 2 parameters. While $G$ and $H$ is a system of 3 equations with 3 parameters and 4 equations with 4 parameters respectively. Their representation in matrices are as follows:

:$$
A=\begin{bmatrix} 1 & 2 \\ 7 & {-11}\end{bmatrix} \\
B=\begin{bmatrix} 13 & 1 & -7 \\ -8 & 21 & -1 \\ 17 & -6 & 1\end{bmatrix}\\
C=\begin{bmatrix} 9 & 40 & 1 & 3 \\ 3 & 1 & 4 & -81 \\ -6 & -5 & 41 & -11 \\ 51 & 1 & -3 & 1 \end{bmatrix}
$$

### Declaring Matrices

In this laboratory activity, a system of linear equations will be represented as matrices. The things or numbers included in matrices are referred to as the matrix's elements. Matrixes have a collection of list-like structures because these items are grouped and sorted in rows and columns. This generalization may be expressed in the same way in the following equation:

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [5]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [6]:
## Declaring a 2 x 2 matrix
A = np.array([
    [3, 5],
    [7, 9]
])
describe_mat(A)

Matrix:
[[3 5]
 [7 9]]

Shape:	(2, 2)
Rank:	2



In [7]:
G = np.array([
    [3,4,17],
    [24,3,9]
])
describe_mat(G)

Matrix:
[[ 3  4 17]
 [24  3  9]]

Shape:	(2, 3)
Rank:	2



In [8]:
## Declaring a 3 x 2 matrix
B = np.array([
    [0, 5],
    [9, 8],
    [3, 1]
])
describe_mat(B)

Matrix:
[[0 5]
 [9 8]
 [3 1]]

Shape:	(3, 2)
Rank:	2



In [9]:
H = np.array([5,6,7,8])
describe_mat(H)

Matrix:
[5 6 7 8]

Shape:	(4,)
Rank:	1



## Categorizing Matrices

Matrices have different types, and they can be classified according to shape and element values.

### According to shape

#### Row and Column Matrices

These are matrices that are also known as "Row and Column Vectors." Row Matrices is described by a single row that has a shape of 1 x n, while Column Matrices is defined as a single column with a shape of n x 1. A row is displayed vertically, and a column is shown horizontally. [4]

In [10]:
## Declaring a Row Matrix

row_mat1D = np.array([
    3, 7, 5, -9
]) ## this is a 1-D Matrix with a shape of (4,), it's not really considered as a row matrix.
row_mat2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,4)
describe_mat(row_mat1D)
describe_mat(row_mat2D)

Matrix:
[ 3  7  5 -9]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [11]:
## Declaring a Column Matrix

colu_mat = np.array([
    [30],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(colu_mat)

Matrix:
[[30]
 [ 2]
 [ 5]]

Shape:	(3, 1)
Rank:	2



#### Square Matrices

The matrices in Square Matrices are arranged in such a way that the sizes of both row and column are equal. In the code cell below, we can distinguish if the matrix is a square matrix or not through the descriptor function, which will print out True or False after the "Is Square:" [5]

In [12]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [13]:
square_mat = np.array([
    [3,7,9],
    [5,1,3],
    [4,2,8]
])

non_square_mat = np.array([
    [4,9,4],
    [5,3,7]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[3 7 9]
 [5 1 3]
 [4 2 8]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[4 9 4]
 [5 3 7]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix

The term "null" simply means "empty". In a Null matrix, it is a type of matrix that does not contain any element. [6]

In [14]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [15]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


#### Zero Matrix

With Zero Matrix, it is easily understood that the elements to be inputted should be zero (0) only regardless of whether the matrix is a square, rectangle, or a row. [6]

In [16]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

Notwithstanding whether the matrix is a row, square, or rectangle, the elements should all be one (1) only. [7] 

In [17]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

From the word itself, it is a type of matrix wherein the elements that are not in the diagonal of the matrix will be automatically zero, and the elements that are non-zero will be placed diagonally in a square matrix. [5]

In [18]:
np.array([
    [7,0,0],
    [0,4,0],
    [0,0,8]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[7, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [19]:
d = np.diag([7,4,8,1])
d.shape[0] == d.shape[1]
d

array([[7, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 1]])

#### Identity Matrix

In this type of matrix, the elements at the diagonal of a matrix are all one (1), and the rest are zero (0). Also known to be a special diagonal matrix and it has two ways; the "np.eye" and "np.identity" [5]

In [20]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.identity(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

It is a matrix in which the values under the diagonal of the matrix will be equivalent to zero, while the values declared will only appear above the diagonal. [5]

In [22]:
np.array([
    [4,1,5,7,1],
    [0,-9,-5,8,1],
    [0,0,7,-11,1],
    [0,0,0,6,1]
])

array([[  4,   1,   5,   7,   1],
       [  0,  -9,  -5,   8,   1],
       [  0,   0,   7, -11,   1],
       [  0,   0,   0,   6,   1]])

#### Lower Triangular Matrix

This type of matrix is the opposite of the Upper Triangular Matrix. Wherein there are no values or the elements to appear is zero above the diagonal of the matrix. The values declared are under the diagonal. [5]

In [23]:
np.array([
    [5,6,0,0],
    [6,7,14,0],
    [-1,3,9,-2]
])

array([[ 5,  6,  0,  0],
       [ 6,  7, 14,  0],
       [-1,  3,  9, -2]])

In [24]:
np.array([
    [5,0,0],
    [6,14,0],
    [-1,9,-2]
])

array([[ 5,  0,  0],
       [ 6, 14,  0],
       [-1,  9, -2]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

$$
\theta = \begin{bmatrix} 5 & 3 & -1 \end{bmatrix} \\
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

$$
A=\begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix} \\
$$

3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \left\{\begin{array}
1p_1 + 7p_2 +8 p_3\\
2p_1 + 2p_2 + 2p_3\\
4p_1 + 6p_2 + 7p_3
\end{array}\right.
$$

$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix} \\
$$




4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

$$
G = \left\{\begin{array}
1p_1 \\
2p_1 + 2p_2 \\
4p_1 + 6p_2 + 7p_3
\end{array}\right.
$$

$$
G=\begin{bmatrix} 1 & 0 & 0\\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix} \\
$$


In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

In [ ]:
I = np.triu(G)
I

array([[1, 7, 8],
       [0, 2, 2],
       [0, 0, 7]])

# Matrix Algebra

In Matrix Algebra, the established matrices can be evaluated through different operations such as Addition, Subtraction, and Element-wise Multiplication.

### Addition

In [ ]:
A = np.array([
    [3,4],
    [5,7],
    [3,2]
])
B = np.array([
    [21,-2],
    [3,0],
    [1,11],
])
A+B

array([[24,  2],
       [ 8,  7],
       [ 4, 13]])

In [ ]:
5+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[ 8,  9],
       [10, 12],
       [ 8,  7]])

### Subtraction

In [ ]:
A-B

array([[-18,   6],
       [  2,   7],
       [  2,  -9]])

In [ ]:
2-B

array([[-19,   4],
       [ -1,   2],
       [  1,  -9]])

In [ ]:
4-B ==3*np.ones(B.shape)-B

array([[False, False],
       [False, False],
       [False, False]])

### Element-wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

array([[63, -8],
       [15,  0],
       [ 3, 22]])

In [ ]:
6*A

array([[18, 24],
       [30, 42],
       [18, 12]])

In [ ]:
A@B

In [ ]:
alpha=9**-9
A/(alpha+B)

array([[ 1.42857143e-01, -2.00000000e+00],
       [ 1.66666667e+00,  2.71194342e+09],
       [ 2.99999999e+00,  1.81818182e-01]])

In [ ]:
np.add(A,B)

array([[24,  2],
       [ 8,  7],
       [ 4, 13]])

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [37]:
#(Create a function named mat_desc() that througouhly describes a matrix, it should:
#Displays the shape, size, and rank of the matrix.
#Displays whether the matrix is square or non-square.
#Displays whether the matrix is an empty matrix.)
#Displays if the matrix is an identity, ones, or zeros matrix

def mat_desc(matrix):
    matrix = np.array(matrix)
    square = False
    print(matrix)
    print("-----------------------------------------------------")
    print("According to Shape,Size & Rank:")
    print(f'Shape:\t{matrix.shape}\nSize:\t{matrix.size}\nRank:\t{matrix.ndim}\n')
    print("-----------------------------------------------------")
    print("Matrix Classifications:")
    print("This sample matrix is a ____")
    if(matrix.shape[0] == matrix.shape[1]):
        square = True
        print('- Square Matrix')
    else:
        print('- Non-Square Matrix')
    if(matrix.shape[0] == 0 and matrix.shape[1] == 0):
        print('- Null/Empty Matrix')
    else:
        print('- Not an Empty Matrix')
    identity = np.identity(matrix.shape[0])
    if(square and (identity == matrix).all()):
        print('- Identity Matrix')
    else:
        print('- Not an Identity Matrix')
    one = np.ones((matrix.shape[0], matrix.shape[1]))
    if((one == matrix).all()):
        print('- Ones Matrix')
    else:
        print('- Not a Ones Matrix')
    zero = np.zeros((matrix.shape[0], matrix.shape[1]))
    if((zero == matrix).all()):
        print('- Zero Matrix')
    else:
        print('- Non-Zero Matrix')

In [38]:
#(Create a function named mat_desc() that througouhly describes a matrix, it should:
#Displays the shape, size, and rank of the matrix.
#Displays whether the matrix is square or non-square.
#Displays whether the matrix is an empty matrix.)
#Displays if the matrix is an identity, ones, or zeros matrix

def mat_desc(matrix):
    matrix = np.array(matrix)
    square = False
    print(matrix)
    print("-----------------------------------------------------")
    print("According to Shape,Size & Rank:")
    print(f'Shape:\t{matrix.shape}\nSize:\t{matrix.size}\nRank:\t{matrix.ndim}\n')
    print("-----------------------------------------------------")
    print("Matrix Classifications:")
    print("This sample matrix is a ____")
    if(matrix.shape[0] == matrix.shape[1]):
        square = True
        print("- Square Matrix")
    else:
        print("- Non-Square Matrix")
    if matrix.size == 0:
        print("- Null/Empty Matrix")
    else:
        print("- Not an Empty Matrix")
    identity = np.identity(matrix.shape[0])
    if(square and (identity == matrix).all()):
        print("- Identity Matrix")
    else:
        print("- Not an Identity Matrix")
    one = np.ones((matrix.shape[0], matrix.shape[1]))
    if((one == matrix).all()):
        print("- Ones Matrix")
    else:
        print("- Not a Ones Matrix")
    zero = np.zeros((matrix.shape[0], matrix.shape[1]))
    if((zero == matrix).all()):
        print("- Zero Matrix")
    else:
        print("- Non-Zero Matrix")

In [39]:
print("#Sample Matrix 1")
M = np.array([
    [4,18,12,16],
    [7,14,21,28],
    [8,16,24,32],
    [9,18,27,36]
])
mat_desc(M)

#Sample Matrix 1
[[ 4 18 12 16]
 [ 7 14 21 28]
 [ 8 16 24 32]
 [ 9 18 27 36]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Non-Zero Matrix


In [40]:
print("#Sample Matrix 2")
P = np.array([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0],   
])
mat_desc(P)

#Sample Matrix 2
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(3, 4)
Size:	12
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Non-Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Zero Matrix


In [41]:
print("#Sample Matrix 3")
G = np.zeros((4,4))
mat_desc(G)

#Sample Matrix 3
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Zero Matrix


In [42]:
print("#Sample Matrix 4")
J = np.eye(4)

mat_desc(J)

#Sample Matrix 4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
- Not an Empty Matrix
- Identity Matrix
- Not a Ones Matrix
- Non-Zero Matrix


In [43]:
print("#Sample Matrix 4")
A = np.array([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])
mat_desc(A)

#Sample Matrix 4
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(4, 4)
Size:	16
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Ones Matrix
- Non-Zero Matrix


In [44]:
print("#Sample Matrix 5")
Z = np.array([
    [1,1,1,1],
    [1,22,11,23],
    [4,8,12,16],
    [3,3,6,8],
    [21,4,9,8],

])
mat_desc(Z)

#Sample Matrix 5
[[ 1  1  1  1]
 [ 1 22 11 23]
 [ 4  8 12 16]
 [ 3  3  6  8]
 [21  4  9  8]]
-----------------------------------------------------
According to Shape,Size & Rank:
Shape:	(5, 4)
Size:	20
Rank:	2

-----------------------------------------------------
Matrix Classifications:
This sample matrix is a ____
- Non-Square Matrix
- Not an Empty Matrix
- Not an Identity Matrix
- Not a Ones Matrix
- Non-Zero Matrix


### Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [45]:
##Create a function named mat_operations() that takes in two matrices a input parameters it should:
#Determines if the matrices are viable for operation and returns your own error message 
#if they are not viable.
#Returns the sum of the matrices.
#Returns the difference of the matrices.
#Returns the element-wise multiplication of the matrices.
#Returns the element-wise division of the matrices.

def mat_operations(matrix_A, matrix_B):
    matrix_A = np.array(matrix_A)
    matrix_B = np.array(matrix_B)
    print('Matrix A:', matrix_A)
    print('Matrix B:', matrix_B)
    if(matrix_A.shape != matrix_B.shape):
        print('Matrix Error: The operation is not viable.')
        return
    print('By Addition: Sum of Matrices:')
    matrix_sum = matrix_A + matrix_B
    print(matrix_sum)
    print('By Subtration: Difference of Matrices:')
    matrix_diff = matrix_A - matrix_B
    print(matrix_diff)
    print('By Element-wise Multiplication of Matrices:')
    matrix_multiply = np.multiply(matrix_A, matrix_B)
    print(matrix_multiply)
    print('By Element-wise Division of Matrices:')
    matrix_divide = np.divide(matrix_A, matrix_B)
    print(matrix_divide)

In [46]:
print("#Sample Matrix 1")
matrix_A = np.array([
    [10,2,3],
    [3,4,3], 
                        
]) 
matrix_B= np.array([
    [1,2,1],
    [8,3,7]           

])
mat_operations(matrix_A, matrix_B)

#Sample Matrix 1
Matrix A: [[10  2  3]
 [ 3  4  3]]
Matrix B: [[1 2 1]
 [8 3 7]]
By Addition: Sum of Matrices:
[[11  4  4]
 [11  7 10]]
By Subtration: Difference of Matrices:
[[ 9  0  2]
 [-5  1 -4]]
By Element-wise Multiplication of Matrices:
[[10  4  3]
 [24 12 21]]
By Element-wise Division of Matrices:
[[10.          1.          3.        ]
 [ 0.375       1.33333333  0.42857143]]


In [47]:
print("#Sample Matrix 2")
matrix_A = np.array([
    [4,2,3,7],
    [3,4,3,1], 
    [11,4,9,2]
                        
]) 
matrix_B= np.array([
    [1,2,1],
    [8,3,7]           

])
mat_operations(matrix_A, matrix_B)

#Sample Matrix 2
Matrix A: [[ 4  2  3  7]
 [ 3  4  3  1]
 [11  4  9  2]]
Matrix B: [[1 2 1]
 [8 3 7]]
Matrix Error: The operation is not viable.


In [48]:
print("#Sample Matrix 3")
mat_operations([[4, 2, 3], [4,1,9], [7,3,5]], [[6,2,1],[4,4,6]])
print("-----------------------------------------------------")
print("#Sample Matrix 4")
mat_operations([[3,2,1,9,1.5], [1.01,2,3,1.2,1], [8,1,8,9,2]], [[5,4,1,3,8],[8,3,4,4.1,2],[2,1,2,3,3]])
print("-----------------------------------------------------")
print("#Sample Matrix 5")
mat_operations([[1, 2, 4,2], [8,16,23,1], [4,3,1,7]], [[2,2,2,2]])

#Sample Matrix 3
Matrix A: [[4 2 3]
 [4 1 9]
 [7 3 5]]
Matrix B: [[6 2 1]
 [4 4 6]]
Matrix Error: The operation is not viable.
-----------------------------------------------------
#Sample Matrix 4
Matrix A: [[3.   2.   1.   9.   1.5 ]
 [1.01 2.   3.   1.2  1.  ]
 [8.   1.   8.   9.   2.  ]]
Matrix B: [[5.  4.  1.  3.  8. ]
 [8.  3.  4.  4.1 2. ]
 [2.  1.  2.  3.  3. ]]
By Addition: Sum of Matrices:
[[ 8.    6.    2.   12.    9.5 ]
 [ 9.01  5.    7.    5.3   3.  ]
 [10.    2.   10.   12.    5.  ]]
By Subtration: Difference of Matrices:
[[-2.   -2.    0.    6.   -6.5 ]
 [-6.99 -1.   -1.   -2.9  -1.  ]
 [ 6.    0.    6.    6.   -1.  ]]
By Element-wise Multiplication of Matrices:
[[15.    8.    1.   27.   12.  ]
 [ 8.08  6.   12.    4.92  2.  ]
 [16.    1.   16.   27.    6.  ]]
By Element-wise Division of Matrices:
[[0.6        0.5        1.         3.         0.1875    ]
 [0.12625    0.66666667 0.75       0.29268293 0.5       ]
 [4.         1.         4.         3.         0.66666667]]
-

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".

This laboratory report has enhanced the students' knowledge about matrices and programming using the Google Colab again. The students were able to apply the matrices in Python in line with the linear system of equations and perform different operations and techniques. Translating matrices was also done, and their classification was further understood through different codes. As the students executed the commands, they were able to determine the importance of the import command and other variables that needed to be called out in order for the codes to run. Moreover, different types of matrices were introduced and categorized according to their shape and element values. 

In recap, according to shape are Row and Column Matrices and Square Matrices, while according to element values are Null Matrix, Zero Matrix, Ones, Matrix, Diagonal Matrix, Identity Matrix, Upper Triangular, and Lower Triangular. Matrix Algebra was also taught and applied wherein there are three operations used: Addition, Subtraction, and Element-wise Multiplication. Through the use of different codes in representing matrices, there were also other codes taught to show matrices in a shorter or easier way. In addition, the students were able to evaluate their understanding through performing the practice provided and the tasks by the instructor.    

With regards to the real-life application of matrices, it is undeniable that there are a myriad of things that we have right now that apply concepts and principles of matrices. Matrices have many significant applications that have a great impact on the modern world.  The impact of matrices and their applications in the mathematical world is widespread because they serve as a foundation for many theories and practices. Computer systems, image processing, battery outputs and the study of electric circuits and quantum mechanics are some of the important applications of matrices that undeniably influence the field of science, mathematics and technology. Various problems relating to science and technology could be solved through the application of matrices because matrices could be utilized to provide rapid approximations to more complex calculations. Matrices also play a vital role in scientific methods and research as they are utilized in plotting graphs, data analysis and statistics. Through those applications, matrices could greatly influence solving problems and contributing to advancements of various different fields especially in the field of technology.
